version: '3'

services:
  servidor:
    build:
      context: ./server
      dockerfile: servidor.dockerfile
    image: servidor
    ports:
      - "8080:8080"
  
  post_client:
    build:
      context: ./client
      dockerfile: post_client.dockerfile
    image: post_client
    depends_on:
      - servidor
  vehicle_client:
    build:
      context: ./client
      dockerfile: vehicle_client.dockerfile
    image: vehicle_client
    depends_on:
      - servidor